project:
  type: website
  output-dir: docs

website:
  title: "Knoxville Aquarium"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - exhibits.qmd
      - site.qmd
      - utility.qmd
      - comparisons.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



