---
title: "About"
---

This was created on a Saturday morning (Aug 16, 2025) by Brian O'Meara, a natural history enthusiast living in Oak Ridge, TN, but NOT by any means an architect or philanthropist, while sitting in a hammock in his backyard. It reflects a quick inspirational idea for an unused site, not a full project proposal. I freely release this idea into the world -- anyone should feel free to run with it and modify it as they see fit, with no permission required from me! I'm not volunteering to lead an initiative for this -- I'm overcommitted to many things as is, so someone else would need to lead this if you want to see it come to fruition. If you want to reach out to me, omeara.brian@gmail.com. Also, if this does become a real thing, I'll happily (and without cost) transfer over the domain name if it'd help you.

Note that nothing written here implies any endorsement by any current, past, or future employers, other colleagues, philanthropies, government officials, etc. I just like looking at fish and helping people learn about the natural world, so when I saw that the proposed science museum site was now fallow, I thought, "you know what'd be neat?" and made this site.