---
title: "Comparisons"
---

There are at least three other nearby public aquariums:

* [**Ripley's Aquarium of the Smokies**](https://www.ripleys.com/attractions/ripleys-aquarium-of-the-smokies): This is about an hour away in Gatlinburg: within a feasible bus trip for students in the Knoxville and surrounding areas. It has some stunning exhibits.
* [**Tennessee Aquarium**](https://tnaqua.org): A spectacular aquarium in Chattanooga, about 1.75 hours away from the proposed Knoxville Aquarium site. It has two main buildings, one primarily for freshwater (River Journey) and one primarily saltwater (Ocean Journey), as well as an IMAX theater. It also has a robust conservation arm. One could imagine the proposed Knoxville Aquarium being a branch or affiliate of the Tennessee Aquarium (this idea has not been discussed at all with the Tennessee Aquarium, it's just a thought).
* [**Georgia Aquarium**](https://www.georgiaaquarium.org): Located in Atlanta (over three hours away), it is perhaps best known for its whale sharks.

However, these are not the only "fishy" things around here. 

* [**Conservation Fisheries**](https://www.conservationfisheries.org): A nonprofit that for over three decades has been raising endangered and other at-risk fish, including many of the amazing rare fish of Tennessee.
* [**Sturgeon Reintroduction**](https://www.tn.gov/twra/wildlife/fish/sturgeon.html): groups within the Tennesseee Wildlife and Fisheries Agency, Tennessee Valley Authority, US Fish & Wildlife Service, the University of Tennessee, the Tennessee Aquarium, and others have been working to [re-introduce and monitor](https://www.wbir.com/article/tech/science/environment/resurgin-sturgeon-east-tennessees-protected-dinosaur-fish-are-finally-growing-into-adults/51-b582532d-2d27-4103-a8a3-99615fceffe6) these massive, long-lived, oddly-shaped fish for decades.
* [**Etnier Ichthyological Collection**](https://tennfish.utk.edu): It holds nearly half a million fish specimens from all around the planet. It can be used for everything from looking at rates of spread of invasive species to helping to determine whether a group of fish are one species or two to understanding changes in pollution over time.
* **Fish Research**: This area of the world is home to a huge amount of fish biodiversity: the many streams and rivers passing down ancient mountains has led to a radiation of many different forms. We also have many caves with their own associated fauna. Some current fish projects at UTIA are [here](https://naturalresources.tennessee.edu/research/) and some news release from the UTK Department of Ecology and Evolutionary Biology are [here](https://eeb.utk.edu/category/fish/). 
* [**iNaturalist**](https://www.inaturalist.org): A community science project useful for people to identify what's around them and for scientists to learn about locations of species. See [here](https://www.inaturalist.org/observations?place_id=45&taxon_id=47178&view=species) for ray-finned fish identified in the Knoxville region, for example.
* [**Great Smoky Mountains National Park**](https://www.nps.gov/grsm): It's just up the road for people from Knoxville, but it's one of the world's premier natural history locations. [Here](https://www.nps.gov/grsm/learn/nature/fish.htm) is information on the fish in the park, for example.
