---
title: "Exhibits"
---

A common approach to aquariums is doing greatest hits: fish of the Amazon, coral reefs, sharks, etc., plus a tank or two of local fish. That would be possible here, but it's such an amazing place that one could focus it on just this region. Another twist could be adding a paleo-aquarium component: closest relatives of the animals that USED to be here in the past, back when a sea covered this region (we can still find marine fossils in Tennessee). Some potential ideas:

## Darters of Tennessee

<iframe width="560" height="315" src="https://www.youtube.com/embed/vmstoEuW1F4?si=73hRPVhHxx6AHQL_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

These small fish are abundant in freshwater streams. They are like underwater peacocks with their vivid breeding colors. People can learn about them at the aquarium and then go off and see them snorkeling in the many rivers in the area.

## Freshwater Mussels

A major industry in the area used to be [pearls and buttons](https://mcclungmuseum.utk.edu/exhibitions/tennessee-freshwater-mussels/) from mother-of-pearl from the mussels abundant when streams ran cold and clear. There is also spectacular natural history, like mussels that have "lures" that attract fish so they can shoot tiny Pac-Man like larvae into their gills (the video below is about Missouri, but we have similar ones in Tennessee):

<iframe width="560" height="315" src="https://www.youtube.com/embed/I0YTBj0WHkU?si=oCOQP0W0_ZglOHS3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Cavefish

The limestone and other rocks that make up much of this region easily get eroded away to make caves with unique animals. An exhibit for this could be spectacular: go to an artficial "cave" in the basement with rocks all around, and with exhibits with cavefish, crayfish, cave spiders and crickets, and more. There are whole ecosystems under our feet that most of us never see.

<iframe width="560" height="315" src="https://www.youtube.com/embed/d_WNBuplKg8?si=bruSeDvUY7R7MDwi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Paleo-Aquarium

This part of Tennessee is rich in marine fossils, because it [used to be under an ocean](https://tnmuseum.org/junior-curators/posts/tennesea) hundreds of millions years ago. Let's recreate that ocean by showing the closest relatives to the organisms that used to live in it. They are not a perfect match since they have changed (the closest living relative to a T. rex is any modern bird, but a chicken coop makes for a bad "Return to the Cretaceous" exhibit), but there are often living examples that are similar. For example, crinoid fossils are abundant, and there are living crinoids, but they are very rarely exhibited in aquariums (they are hard to maintain). 

<iframe width="560" height="315" src="https://www.youtube.com/embed/7vdWvOlU-bY?si=nqszfGhAVw250Pcw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

  