---
title: "Utility"
---

Aquariums are just fun places. But what could be some of the utility of one in Knoxville? Some of this is adapted from the [advocacy for a science museum in Knoxville](https://www.knoxvilletn.gov/government/city_departments_offices/urban_design_and_development/strategic_projects/knoxville_science_museum__former_safety_building_), but there are additional benefits as well.

* **Longer stays in Knoxville**: A small regional aquarium, no matter how lovely, probably will not draw tourists from far away on its own. But it makes people more likely to spend more time in Knoxville. Coming for a Vols football game? Book an extra night and check out the Knoxville Aquarium and the [Women's Basketball Hall of Fame](https://wbhof.com), maybe take a [dinner cruise](https://www.tnriverboat.com). Making Knoxville a weekend destination not just an event destination captures a lot more tourist dollars. The proximity of the new aquarium to the [Knoxville Civic Auditorium and Coliseum](https://www.knoxvillecoliseum.com) will help with that, too.
* **More event space**: A source of revenue for aquariums is renting out space for events. For conventions especially, having a place near a convention site (so no need to arrange transportation) but with a different feel can be great for receptions or mixers: an aquarium is a perfect place for this; see example pages from the [New England Aquarium](https://www.neaq.org/engage/host-an-event/) in Boston, the [Shedd Aquarium](https://www.sheddaquarium.org/plan-a-visit/plan-your-event) in Chicago, or the [Florida Aquarium](https://www.flaquarium.org/events/host-an-event/venue-spaces/) in Tampa. We can attract more conventions to Knoxville with an aquarium. It would also be great for weddings.
* **Activate this part of Knoxville**: More foot traffic, especially during the day.
* **Education**: Easy accessibility from I-40 and I-75 means schools from all over the region can get to the aquarium easily. And a focus on Tennnessee fauna could lead to alignment with Tennessee state science standards.
* **Conservation**: The Knoxville Aquarium would be located a block from the Tennessee River, which is cleaner than it has been in decades and is continuing to improve. Visitors could learn about the truly astounding variety of life in the river and its tributaries and ongoing efforts to restore it.